apiVersion: v1
kind: Service
metadata:
  name: recast-ui
spec:
  selector:
    app: recast
    tier: frontend
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  type: ClusterIP