.validate-oas:
  stage: prepare
  needs: []
  image: node:14
  when: always
  script:
    - npm install -g swagger-cli@$SWAGGER_CLI_VERSION
    - swagger-cli validate $OAS_FILE
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never