openapi: 3.0.3
info:
  title: Recast Models
  description: Models for Recast Project
  version: 1.0.0

paths: {}

components:
  schemas:
    Processes:
      properties:
        processes:
          type: array
          items:
            $ref: '#/components/schemas/Process'

    Process:
      required:
        - id
      properties:
        id:
          type: integer
        createdAt:
          type: string
          format: date-time
        name:
          type: string
        steps:
          nullable: true
          type: array
          items:
            $ref: '#/components/schemas/Step'

    Step:
      properties:
        id:
          type: integer
        createdAt:
          type: string
          format: date-time
        processId:
          type: string
        name:
          type: string
        stepProperties:
          type: array
          items:
            $ref: '#/components/schemas/StepProperty'

    StepProperty:
      type: object
      properties:
        id:
          type: integer
        createdAt:
          type: string
          format: date-time
        stepId:
          type: string
        name:
          type: string
        defaultValue:
          nullable: true
          type: string
        description:
          type: string
        type:
          type: string
          enum:
            - text
            - number
            - file

    Elements:
      properties:
        processes:
          type: array
          items:
            $ref: '#/components/schemas/Element'

    Element:
      properties:
        id:
          type: integer
        createdAt:
          type: string
          format: date-time
        name:
          type: string
        processId:
          type: string
        elementProperties:
          type: array
          items:
            $ref: '#/components/schemas/ElementProperty'

    ElementProperty:
      properties:
        id:
          type: integer
        createdAt:
          type: string
          format: date-time
        elementId:
          type: string
        stepProperty:
          $ref: '#/components/schemas/StepProperty'
        value:
          type: string

    Profile:
      required:
        - id
        - email
      properties:
        id:
          type: string
        updatedAt:
          type: string
          format: date-time
        fullName:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        username:
          type: string
        avatarUrl:
          type: string
