apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
data:
  # Projekt spezifischer Token, dessen einzige Berechtigung read-access auf der Container-Registry des Projekts ist.
  .dockerconfigjson: eyJhdXRocyI6eyJnaXRsYWItcmVnaXN0cnkud29ncmEuY29tIjp7InVzZXJuYW1lIjoicmVhZF9yZWdpc3RyeSIsInBhc3N3b3JkIjoiZ2xwYXQtc3BHelJndWpZcTRvZk5mZTVxVWIiLCJhdXRoIjoiY21WaFpGOXlaV2RwYzNSeWVUcG5iSEJoZEMxemNFZDZVbWQxYWxseE5HOW1UbVpsTlhGVllnPT0ifX19
type: kubernetes.io/dockerconfigjson
