include:
  - local: 'gitlab/shared/.gitlab-ci.build-production.yml'

.build-frontend:
  stage: build
  needs: [ ]
  image: $CI_REGISTRY/developer/images/node-java:node-16-jre-11
  script:
    - cd $DIR
    - npm ci --cache .npm_cache
    - npm run lint
    - npm run build
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: $CI_COMMIT_REF_NAME =~ /^hotfix/
    - if: '$CI_COMMIT_TAG'

.build-frontend-dev:
  stage: build
  needs: []
  image: $CI_REGISTRY/developer/images/node-java:node-16-jre-11
  script:
    - cd $DIR
    - npm ci --cache .npm_cache
    - npm run lint
    - npm run build-dev
  rules:
    - if: $CI_COMMIT_BRANCH != "main" && $CI_COMMIT_REF_NAME !~ /^hotfix/ && $CI_COMMIT_TAG == null

build-frontend:
  extends:
    - .build-frontend
  variables:
    DIR: 'apps/recast'
    IMG_NAME: 'frontend'
  artifacts:
    paths:
      - apps/recast/dist/recast
  cache:
    key: frontend
    paths:
      - apps/recast/node_modules
      - apps/recast/.npm_cache
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: $CI_COMMIT_REF_NAME =~ /^hotfix/
    - if: '$CI_COMMIT_TAG'

build-frontend-dev:
  extends:
    - .build-frontend-dev
  variables:
    DIR: 'apps/recast'
    IMG_NAME: 'frontend'
  artifacts:
    paths:
      - apps/recast/dist/recast
  cache:
    key: frontend
    paths:
      - apps/recast/node_modules
      - apps/recast/.npm_cache
  rules:
    - if: $CI_COMMIT_BRANCH != "main" && $CI_COMMIT_REF_NAME !~ /^hotfix/ && $CI_COMMIT_TAG == null

build-frontend-image:
  extends:
    - .build-production
  needs:
    - build-frontend
  dependencies:
    - build-frontend
  variables:
    DOCKERFILE: 'apps/recast/Dockerfile'
    IMG_NAME: 'frontend'
    BUILD_CONTEXT: 'apps/recast'
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: $CI_COMMIT_REF_NAME =~ /^hotfix/
    - if: '$CI_COMMIT_TAG'

build-frontend-image-dev:
  extends:
    - .build-production
  needs:
    - build-frontend-dev
  dependencies:
    - build-frontend-dev
  variables:
    DOCKERFILE: 'apps/recast/Dockerfile'
    IMG_NAME: 'frontend'
    BUILD_CONTEXT: 'apps/recast'
  rules:
    - if: $CI_COMMIT_BRANCH != "main" && $CI_COMMIT_REF_NAME !~ /^hotfix/ && $CI_COMMIT_TAG == null